"use client";

export {
  type PublicSalonProfile,
  type PublicSalonCatalog,
  type PublicSalonCatalogProcedure,
  type PublicSalonCatalogComplex,
  type PublicSalonMaster,
  type PublicDateInterval,
  type PublicSearchSlotsResponse,
  type PublicProcedureSlotsResponse,
  type PublicComplexSlotsResponse,
  type PublicSearchProcedureBody,
  type PublicSearchComplexBody,
  type PublicBookingCreatePayload,
  type PublicBookingVisit,
  type PublicClickResponse,
  type PublicClickMetadata,
  type PublicMarketingCampaign,
  type PublicLinkKind,
  type StoredPublicBookingContext,
  getPublicSalonProfile,
  getPublicSalonCatalog,
  getPublicSalonMasters,
  searchPublicBookingSlots,
  createPublicBooking,
  getPublicBooking,
  getCampaignByLink,
  registerLinkClick,
  buildClickMetadata,
  savePublicBookingContext,
  readPublicBookingContext,
  isAuthorizationGap,
} from "@/lib/api/public-booking";

export {
  type Step,
  type Procedure,
  type ProcedureGroup,
  type SlotInterval,
  type AppointmentResponse,
  type CreateAppointmentPayload,
  BookingApiError,
  getSalonProcedures,
  searchSalonSlots,
  createSalonAppointment,
  getSalonAppointment,
  getAppointment,
  getWalletUrl,
  getAppleWalletUrl,
  getGoogleWalletUrl,
} from "@/lib/api/booking";
